###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

# NOTE: To setup SAND with InfluxDB collecting metrics from Telegraf do the following:
# make dist
# docker-compose -f docker-compose-sand.yaml up -d --build
# curl -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE sand"
# curl -XPOST http://localhost:8086/query --data-urlencode 'q=CREATE RETENTION POLICY "default" ON "sand" DURATION INF REPLICATION 1'

# NOTE: To check the logs of an individual service, do:
# docker compose logs <service name>

version: '2'

services:

  hydra:
    build:
      context: .
      dockerfile: Dockerfile-sand
    links:
      # - postgresd:postgresd
#     Uncomment the following line to use mysql instead.
      - mysqld:mysqld
#     Uncomment the following line to use redis instead.
#      - redisd:redisd
      - influxdb
    volumes:
      - hydravolume:/root
    ports:
      - "4444:4444"
      - "4445:4445"
      # Uncomment the following line if you want to send Statsd metrics into the container from the host
      # - "8125:8125/udp"
    environment:
      - LOG_LEVEL=debug
      - ISSUER=http://localhost:4444
      - CONSENT_URL=http://localhost:3000/consent
#     Uncomment the following line to use in-memory db instead.
      # - DATABASE_URL=memory
#     Uncomment the following line to use postgres instead.
      # - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
#     Uncomment the following line to use mysql instead.
      - DATABASE_URL=mysql://root:secret@tcp(mysqld:3306)/mysql?parseTime=true
#     Uncomment the following line to use redis instead.
#      - DATABASE_URL=redis://redisd:6379/0
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
      - SYSTEM_SECRET=some-very-insecure-secret
      - INFLUXDB_HOST=http://influxdb:8086
      - INFLUXDB_DATABASE_NAME=sand
      - ENABLE_STATSD=true
      - STATSD_SAMPLE_RATE=1.0
      - STATSD_ADDRESS=localhost:8125
      - STATSD_PREFIX=SAND
      - TELEGRAF_HOSTNAME=SAND
      # NOTE: Never use the following lines in production
      - TEST_SAND_DANGEROUS_FORCE_HTTP=true
      - TEST_SAND_MIGRATE_DB=true
    restart: unless-stopped
    depends_on:
      # - postgresd
      - mysqld
      - influxdb

  # consent:
  #   environment:
  #     - HYDRA_URL=http://hydra:4444
  #     - HYDRA_CLIENT_ID=admin
  #     - HYDRA_CLIENT_SECRET=demo-password
  #     - NODE_TLS_REJECT_UNAUTHORIZED=0
  #   image: oryd/hydra-consent-app-express:v0.1.6
  #   links:
  #     - hydra
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped

  # postgresd:
  #   image: postgres:9.6
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=hydra
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_DB=hydra

#  Uncomment the following section to use mysql instead.
  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret

#  Uncomment the following section to use redis instead.
#  redisd:
#    image: redis:3.2

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=sand
      # - INVFLUXDB_USER=sand
      # - INFLUXDB_USER_PASSWORD=sand
      # - INFLUXDB_HTTP_AUTH_ENABLED='true'

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=secret
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - influxdb

volumes:
  hydravolume:
    driver: local
